param(
    [ValidateSet("all", "sdk_ts", "types_ts", "sdk_py")]
    [string]$Target = "all",
    [switch]$Check
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
& (Join-Path $PSScriptRoot "validate_contracts.ps1") -Scope all

function Ensure-Directory {
    param([string]$Path)
    if (-not (Test-Path $Path)) {
        New-Item -ItemType Directory -Force -Path $Path | Out-Null
    }
}

function Write-GeneratedFile {
    param(
        [string]$Path,
        [string]$Content
    )
    if ($Check) {
        if (-not (Test-Path $Path)) {
            throw "Generated artifact missing in check mode: $Path"
        }
        $existing = Get-Content -Path $Path -Raw -Encoding UTF8
        if ($existing.TrimEnd("`r", "`n") -ne $Content.TrimEnd("`r", "`n")) {
            throw "Generated artifact out of date: $Path"
        }
        return
    }
    Set-Content -Path $Path -Value $Content -Encoding UTF8
}

function Get-OperationIds {
    Get-ChildItem -Path (Join-Path $repoRoot "contracts\api\openapi") -Filter *.yaml -File | ForEach-Object {
        $raw = Get-Content -Path $_.FullName -Raw -Encoding UTF8
        foreach ($match in [regex]::Matches($raw, 'operationId:\s*([A-Za-z0-9_]+)')) {
            $match.Groups[1].Value
        }
    } | Sort-Object -Unique
}

function Get-JsonSchemaIds {
    Get-ChildItem -Path (Join-Path $repoRoot "contracts\api\jsonschema") -Filter *.json -File | Where-Object { -not $_.BaseName.StartsWith("_") } | ForEach-Object {
        $json = (Get-Content -Path $_.FullName -Raw -Encoding UTF8 | ConvertFrom-Json)
        [PSCustomObject]@{
            Name = $_.BaseName
            Id   = $json.'$id'
        }
    } | Sort-Object Name
}

function Get-EventNames {
    Get-ChildItem -Path (Join-Path $repoRoot "contracts\events") -Recurse -Filter *.json -File | Where-Object { -not $_.BaseName.StartsWith("_") } | ForEach-Object {
        $json = (Get-Content -Path $_.FullName -Raw -Encoding UTF8 | ConvertFrom-Json)
        $json.event_name
    } | Sort-Object -Unique
}

function Get-GovernanceKeys {
    Get-ChildItem -Path (Join-Path $repoRoot "contracts\governance") -Recurse -Filter *.json -File | Where-Object { -not $_.BaseName.StartsWith("_") } | ForEach-Object {
        $json = (Get-Content -Path $_.FullName -Raw -Encoding UTF8 | ConvertFrom-Json)
        foreach ($key in @($json.flag_name, $json.threshold_name, $json.policy_name)) {
            if ($key) { $key }
        }
    } | Sort-Object -Unique
}

$operationIds = Get-OperationIds
$schemaIds = Get-JsonSchemaIds
$eventNames = Get-EventNames
$governanceKeys = Get-GovernanceKeys
if ($Target -in @("all", "types_ts")) {
    $typesDir = Join-Path $repoRoot "packages\generated\types_ts"
    Ensure-Directory $typesDir
    $schemaLines = $schemaIds | ForEach-Object { "  ""$($_.Name)"": ""$($_.Id)""" }
    $eventLines = $eventNames | ForEach-Object { "  ""$_""" }
    $govLines = $governanceKeys | ForEach-Object { "  ""$_""" }
    $content = @(
        "// generated by scripts/generate_contract_artifacts.ps1",
        "export const schemaIds = {",
        ($schemaLines -join ",`n"),
        "} as const;",
        "",
        "export const eventNames = [",
        ($eventLines -join ",`n"),
        "] as const;",
        "",
        "export const governanceKeys = [",
        ($govLines -join ",`n"),
        "] as const;"
    ) -join "`n"
    Write-GeneratedFile -Path (Join-Path $typesDir "contracts.generated.ts") -Content $content
}

if ($Target -in @("all", "sdk_ts")) {
    $sdkTsDir = Join-Path $repoRoot "packages\generated\sdk_ts"
    Ensure-Directory $sdkTsDir
    $operationLines = $operationIds | ForEach-Object { "  ""$_""" }
    $content = @(
        "// generated by scripts/generate_contract_artifacts.ps1",
        "export const operationIds = [",
        ($operationLines -join ",`n"),
        "] as const;",
        "",
        "export type OperationId = typeof operationIds[number];"
    ) -join "`n"
    Write-GeneratedFile -Path (Join-Path $sdkTsDir "openapi.generated.ts") -Content $content
}

if ($Target -in @("all", "sdk_py")) {
    $sdkPyDir = Join-Path $repoRoot "packages\generated\sdk_py"
    Ensure-Directory $sdkPyDir
    $operationLines = $operationIds | ForEach-Object { "    '$_'," }
    $content = @(
        "# generated by scripts/generate_contract_artifacts.ps1",
        "OPERATION_IDS = [",
        ($operationLines -join "`n"),
        "]"
    ) -join "`n"
    Write-GeneratedFile -Path (Join-Path $sdkPyDir "openapi_generated.py") -Content $content
}

Write-Host "Generated contract artifacts for target '$Target'." -ForegroundColor Green
